[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
throne = "6AqWpXAFSEN73NZQFzcAo7mZjCgNEy7fkULwDMSPwddq"

[programs.devnet]
throne = "6AqWpXAFSEN73NZQFzcAo7mZjCgNEy7fkULwDMSPwddq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/**/*.ts"
